baseURL = 'https://saranshchopra.github.io/'
languageCode = 'en-us'
title = 'Saransh Chopra'
publishDir = "docs"

theme = "nightfall"

[params]
user = "welcome"
hostname = "saranshchopra.io"

[params.author]
name = "Saransh Chopra"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/saranshchopra"

[[params.social]]
key = 1
name = "linkedin"
url = "https://linkedin.com/in/saransh-chopra/"

[menu]
[[menu.header]]
name = "research"
weight = 0
url = "/research"